// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Rjy is an autogenerated mock type for the Rjy type
type Rjy struct {
	mock.Mock
}

// Get provides a mock function with given fields: a
func (_m *Rjy) Get(a int) int {
	ret := _m.Called(a)

	var r0 int
	if rf, ok := ret.Get(0).(func(int) int); ok {
		r0 = rf(a)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
